[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
seeds = false
skip-lint = false

[programs.localnet]
wunderland_sol = "ExSiNgfPTSPew6kCqetyNcw8zWMo1hozULkZR1CSEq88"

[programs.devnet]
wunderland_sol = "ExSiNgfPTSPew6kCqetyNcw8zWMo1hozULkZR1CSEq88"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
